/*******************************************************************************
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.60.0.1460
*
********************************************************************************
* Copyright 2023 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

#define ADV_NAME_LEN 13

/* Device address */
wiced_bt_device_address_t cy_bt_device_address = {0x00, 0xA0, 0x50, 0x00, 0x00, 0x00};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x06 };
uint8_t cy_bt_adv_packet_elem_1[ADV_NAME_LEN];
const uint8_t adv_fix_name_len = 9;
const uint8_t adv_fix_name[] = { 0x4B, 0x53, 0x49, 0x2D, 0x44, 0x42, 0x4C, 0x45, 0x2D }; // "KSI-DBLE-"
const uint8_t adv_var_name_len = ADV_NAME_LEN - adv_fix_name_len;

wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] = 
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, 
    },
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = ADV_NAME_LEN,
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, 
    },
};

// Return the length of variable name
uint8_t get_adv_var_name_length(void)
{
    return adv_var_name_len;
}

// Construct advertisement name
void construct_adv_name(uint8_t *var_name, uint8_t var_name_len)
{
    uint8_t idx = 0;

    for(idx = 0; idx < adv_fix_name_len; idx++){

        cy_bt_adv_packet_elem_1[idx] = adv_fix_name[idx];
    }

    for(idx = 0; idx < var_name_len; idx++){

        cy_bt_adv_packet_elem_1[idx+adv_fix_name_len] = var_name[idx];
    }

    cy_bt_adv_packet_data[1].p_data = (uint8_t*)cy_bt_adv_packet_elem_1;
}
